<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-10 at 11:15:55.
 */
class MagentoEnvironmentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MagentoEnvironment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MagentoEnvironment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MagentoEnvironment::getBasePath
     */
    public function testGetBasePath()
    {
        $this->object->setBasePath("testpath");
        $this->assertEquals("testpath", $this->object->getBasePath());
    }

    /**
     * @covers MagentoEnvironment::getDb
     */
    public function testGetDb()
    {
        $this->object->setDb(new mysqli());
        $this->assertInstanceOf('mysqli', $this->object->getDb());
    }

    /**
     * @covers MagentoEnvironment::getGitBranch
     */
    public function testGetGitBranch()
    {
        $this->object->setDbPrefix("prefix");
        $this->assertEquals("prefix", $this->object->getDbPrefix());
    }

    /**
     * @covers MagentoEnvironment::getGitBase
     */
    public function testGetGitBase()
    {
        $this->assertRegExp('|^http.*|', $this->object->getGitBase());
    }

    /**
     * @covers MagentoEnvironment::getOptions
     */
    public function testGetOptions()
    {
        $options = new Options();
        $this->object->setOptions($options);
        $this->assertInstanceOf('Options', $this->object->getOptions());
    }
}
