<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-10 at 11:15:54.
 */
class MyLoggerConfiguratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MyLoggerConfigurator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MyLoggerConfigurator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MyLoggerConfigurator::configure
     * @todo   Implement testConfigure().
     */
    public function testConfigure()
    {
        Logger::configure(array('root'), 'MyLoggerConfigurator');
        $log = Logger::getLogger(__CLASS__);
        $this->assertInstanceOf('Logger', $log);
    }
}
